"""update cv

Revision ID: aebe25e87c0e
Revises: 39e80c7906cd
Create Date: 2025-09-08 13:21:01.088680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebe25e87c0e'
down_revision: Union[str, Sequence[str], None] = '39e80c7906cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'cvs', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cvs', type_='unique')
    op.drop_column('cvs', 'code')
    # ### end Alembic commands ###
