FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Copia o entrypoint e dá permissão
COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh


# Usa o entrypoint para aplicar migrações antes de iniciar o FastAPI
CMD ["./entrypoint.sh"]

